### ISSUE TITLE
RuntimeError: shape mismatch

### ISSUE THREAD

**Issue by allenhaozhu** [twitter-research/sign#2]
It seems like pytorch_sparse issue:
Traceback (most recent call last):
  File "preprocessing.py", line 142, in <module>
    main()
  File "preprocessing.py", line 100, in main
    adj = get_adj(row, col, N, asymm_norm=args.undirected_asymm_norm, set_diag=args.undirected_set_diag, remove_diag=args.undirected_remove_diag)
  File "preprocessing.py", line 19, in get_adj
    adj = adj.set_diag()
  File "/home/zhu044/.local/lib/python3.6/site-packages/torch_sparse/diag.py", line 96, in <lambda>
    self, values, k)
  File "/home/zhu044/.local/lib/python3.6/site-packages/torch_sparse/diag.py", line 47, in set_diag
    new_row[mask] = row
RuntimeError: shape mismatch: value tensor of shape [50238473] cannot be broadcast to indexing result of shape [50056641]

**Comment by Noired** [comment]
Hi allenhaozhu!
We have not encountered this problem so far on our side. Would you kindly provide us the details of your virtual environment so that we can try to reproduce the issue?

**Comment by ayeshasiddika9196** [comment]
reset code
